when:
  - event: tag
    ref: refs/tags/v*

clone:
  git:
    image: docker.io/woodpeckerci/plugin-git:2.9.0
    settings:
      partial: false
      depth: 0
      lfs: false
      recursive: false

steps:
  - name: verify-release
    image: git.wavefunk.io/wavefunk/ci-rust:nightly-2026-01-05
    pull: true
    environment:
      CARGO_HOME: /woodpecker-cache/cargo
      CARGO_TARGET_DIR: /woodpecker-cache/target
      SCCACHE_DIR: /woodpecker-cache/sccache
    volumes:
      - wavefunk-ui-release-cache:/woodpecker-cache
    commands:
      - mkdir -p /woodpecker-cache/cargo /woodpecker-cache/target /woodpecker-cache/sccache
      - version="$(sed -n 's/^version = \"\\(.*\\)\"/\\1/p' Cargo.toml | head -n 1)"
      - test "v$version" = "$CI_COMMIT_TAG"
      - cargo fmt --check
      - cargo test --all-features --locked
      - cargo clippy --all-features --all-targets --locked -- -D warnings
      - cargo package --allow-dirty --locked
      - cargo publish --dry-run --locked --allow-dirty

  - name: publish-crate
    image: git.wavefunk.io/wavefunk/ci-rust:nightly-2026-01-05
    pull: true
    depends_on: [verify-release]
    environment:
      CARGO_HOME: /woodpecker-cache/cargo
      CARGO_REGISTRY_TOKEN:
        from_secret: cargo_registry_token
      CARGO_TARGET_DIR: /woodpecker-cache/target
      SCCACHE_DIR: /woodpecker-cache/sccache
    volumes:
      - wavefunk-ui-release-cache:/woodpecker-cache
    commands:
      - mkdir -p /woodpecker-cache/cargo /woodpecker-cache/target /woodpecker-cache/sccache
      - cargo publish --locked
